#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         5
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true


# Border
bspc config focused_border_color        "#6c71c4"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#
# Autostart
#
# Set display from arandr saved script
sh ~/.screenlayout/monitor.sh &

# Bar
~/.config/polybar/launch.sh &

# Notifications
/usr/bin/dunst &

# Polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Wallpaper
nitrogen --restore &

# Dex
dex -a -s /etc/xdg/autostart/:~/.config/autostart/  

#Picom
#picom -CGb &
picom --config ~/.config/picom.conf &

# Network Applet
nm-applet --indicator &

# Cursor
xsetroot -cursor_name left_ptr &

# Low battery notifier
~/.config/bspwm/scripts/low_bat_notifier.sh

#screensaver 
xscreensaver --nosplash

#automount unmunt gui
udiskie --tray &

#Rules

#bspc rule -a Google-chrome desktop=^1 follow=on
#bspc rule -a kitty desktop=^2 follow=on
#bspc rule -a Thunar desktop=^3 follow=on
bspc rule -a Catfish desktop=^4 follow=on
bspc rule -a Transmission-gtk desktop=^5 follow=on
bspc rule -a Blueman-manager desktop=^6 follow=on
bspc rule -a kitty -e Ranger desktop=^7 follow=on
bspc rule -a vlc state=floating


